services:
  db:
    image: "postgres:17"
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=put_password_here
      - POSTGRES_DB=democraciv

  api:
    build: ./api/
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    build: ./bot/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - api

  meilisearch:
    image: getmeili/meilisearch:v1.10
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=zMaced2bA7yBdrISw-7x0BoCRJOUDYSrHbhrCqK2T_w
    volumes:
      - meili_data:/meili_data
    
volumes:
  postgresdata:
      external: true
  meili_data: