version: "3.8"

services:
  db:
    image: "postgres:13.1"
    ports:
      - "5432:5432"
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_MULTIPLE_DATABASES=democraciv,api_test

  api:
    build: ./api/
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    build: ./bot/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - api