version: "3.8"

services:
  db:
    image: "postgres:16"
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=put_password_here
      - POSTGRES_DB=democraciv

  api:
    build: ./api/
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    build: ./bot/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - api

volumes:
  postgresdata:
      external: true